import { describe, expect, it } from 'vitest';
import { summarizeFileChainLinks } from './file-chain-state.js';
import { groupOrderFileChainLinksForDisplay } from './file-chain.js';

describe('file chain grouping', () => {
  it('merges each printable chain with its paired Zund row', () => {
    const grouped = groupOrderFileChainLinksForDisplay([
      {
        id: 'print-1',
        createdAt: new Date('2026-04-15T11:00:00.000Z'),
        updatedAt: new Date('2026-04-15T11:02:00.000Z'),
        workOrder: { id: 'wo-1', orderNumber: '64586', customerName: 'Mastertag' },
        ripJob: {
          id: 'rip-1',
          status: 'PRINTING',
          hotfolderName: 'ZUND G7',
          ripJobGuid: 'rip-1-guid',
          rippedAt: new Date('2026-04-15T10:55:00.000Z'),
          printStartedAt: new Date('2026-04-15T11:00:00.000Z'),
          printCompletedAt: null,
        },
        linkedBy: null,
        confirmedBy: null,
        status: 'PRINTING',
        printFileName: '24x6.5 Logo Decal-PRINTANDCUT.pdf',
        printFilePath: '\\\\server\\design\\24x6.5 Logo Decal-PRINTANDCUT.pdf',
        printStartedAt: new Date('2026-04-15T11:00:00.000Z'),
        printCompletedAt: null,
        printerName: 'HP Latex 570-2',
        ripMachine: 'RIP-1',
        cutFileName: null,
        cutFilePath: null,
        cutFileSource: null,
        cutFileFormat: null,
        cutId: null,
        linkedAt: null,
        linkedById: null,
        confirmed: false,
        confirmedAt: null,
        confirmedById: null,
        cutStartedAt: null,
        cutCompletedAt: null,
        cutterName: null,
        cutJobName: null,
        cutCopiesDone: null,
        cutCopiesTotal: null,
        zundJobId: null,
        zundMaterialGuid: null,
        cuttingTimeMs: null,
        setupTimeMs: null,
        cutLengthMm: null,
        errorMessage: null,
      },
      {
        id: 'cut-1',
        createdAt: new Date('2026-04-15T11:05:00.000Z'),
        updatedAt: new Date('2026-04-15T11:06:00.000Z'),
        workOrder: { id: 'wo-1', orderNumber: '64586', customerName: 'Mastertag' },
        ripJob: null,
        linkedBy: null,
        confirmedBy: null,
        status: 'CUT_PENDING',
        printFileName: '24x6.5_Logo_Decal-PRINTANDCUT',
        printFilePath: '\\\\server\\cut\\24x6.5_Logo_Decal-PRINTANDCUT',
        printStartedAt: null,
        printCompletedAt: null,
        printerName: null,
        ripMachine: null,
        cutFileName: '24x6.5_Logo_Decal-PRINTANDCUT.zcc',
        cutFilePath: '\\\\server\\cut\\24x6.5_Logo_Decal-PRINTANDCUT.zcc',
        cutFileSource: 'ZUND_CENTER',
        cutFileFormat: '.zcc',
        cutId: 'CUT-1',
        linkedAt: null,
        linkedById: null,
        confirmed: false,
        confirmedAt: null,
        confirmedById: null,
        cutStartedAt: null,
        cutCompletedAt: null,
        cutterName: 'Zund 1',
        cutJobName: '24x6.5_Logo_Decal-PRINTANDCUT',
        cutCopiesDone: null,
        cutCopiesTotal: null,
        zundJobId: 'zund-1',
        zundMaterialGuid: 'mat-1',
        cuttingTimeMs: null,
        setupTimeMs: null,
        cutLengthMm: null,
        errorMessage: null,
      },
      {
        id: 'print-2',
        createdAt: new Date('2026-04-15T10:00:00.000Z'),
        updatedAt: new Date('2026-04-15T10:04:00.000Z'),
        workOrder: { id: 'wo-1', orderNumber: '64586', customerName: 'Mastertag' },
        ripJob: {
          id: 'rip-2',
          status: 'PRINTED',
          hotfolderName: 'ZUND G7',
          ripJobGuid: 'rip-2-guid',
          rippedAt: new Date('2026-04-15T09:55:00.000Z'),
          printStartedAt: new Date('2026-04-15T10:00:00.000Z'),
          printCompletedAt: new Date('2026-04-15T10:04:00.000Z'),
        },
        linkedBy: null,
        confirmedBy: null,
        status: 'PRINTED',
        printFileName: '48x3 Logo Graphic-PRINTANDCUT.pdf',
        printFilePath: '\\\\server\\design\\48x3 Logo Graphic-PRINTANDCUT.pdf',
        printStartedAt: new Date('2026-04-15T10:00:00.000Z'),
        printCompletedAt: new Date('2026-04-15T10:04:00.000Z'),
        printerName: 'HP Latex 570-2',
        ripMachine: 'RIP-1',
        cutFileName: null,
        cutFilePath: null,
        cutFileSource: null,
        cutFileFormat: null,
        cutId: null,
        linkedAt: null,
        linkedById: null,
        confirmed: false,
        confirmedAt: null,
        confirmedById: null,
        cutStartedAt: null,
        cutCompletedAt: null,
        cutterName: null,
        cutJobName: null,
        cutCopiesDone: null,
        cutCopiesTotal: null,
        zundJobId: null,
        zundMaterialGuid: null,
        cuttingTimeMs: null,
        setupTimeMs: null,
        cutLengthMm: null,
        errorMessage: null,
      },
      {
        id: 'cut-2',
        createdAt: new Date('2026-04-15T10:06:00.000Z'),
        updatedAt: new Date('2026-04-15T10:20:00.000Z'),
        workOrder: { id: 'wo-1', orderNumber: '64586', customerName: 'Mastertag' },
        ripJob: null,
        linkedBy: null,
        confirmedBy: null,
        status: 'CUT_COMPLETE',
        printFileName: '48x3_Logo_Graphic-PRINTANDCUT',
        printFilePath: '\\\\server\\cut\\48x3_Logo_Graphic-PRINTANDCUT',
        printStartedAt: null,
        printCompletedAt: null,
        printerName: null,
        ripMachine: null,
        cutFileName: '48x3_Logo_Graphic-PRINTANDCUT.zcc',
        cutFilePath: '\\\\server\\cut\\48x3_Logo_Graphic-PRINTANDCUT.zcc',
        cutFileSource: 'ZUND_CENTER',
        cutFileFormat: '.zcc',
        cutId: 'CUT-2',
        linkedAt: null,
        linkedById: null,
        confirmed: false,
        confirmedAt: null,
        confirmedById: null,
        cutStartedAt: new Date('2026-04-15T10:12:00.000Z'),
        cutCompletedAt: new Date('2026-04-15T10:20:00.000Z'),
        cutterName: 'Zund 1',
        cutJobName: '48x3_Logo_Graphic-PRINTANDCUT',
        cutCopiesDone: 2,
        cutCopiesTotal: 2,
        zundJobId: 'zund-2',
        zundMaterialGuid: 'mat-2',
        cuttingTimeMs: 480000,
        setupTimeMs: 120000,
        cutLengthMm: 3120,
        errorMessage: null,
      },
    ] as any);

    expect(grouped).toHaveLength(2);
    expect(grouped[0]).toMatchObject({
      printFileName: '24x6.5 Logo Decal-PRINTANDCUT.pdf',
      cutFileName: '24x6.5_Logo_Decal-PRINTANDCUT.zcc',
      hasPrintFile: true,
      hasCutFile: true,
      printStatus: 'IN_PROGRESS',
      cutStatus: 'PENDING',
    });
    expect(grouped[1]).toMatchObject({
      printFileName: '48x3 Logo Graphic-PRINTANDCUT.pdf',
      cutFileName: '48x3_Logo_Graphic-PRINTANDCUT.zcc',
      hasPrintFile: true,
      hasCutFile: true,
      printStatus: 'COMPLETED',
      cutStatus: 'COMPLETED',
    });

    expect(summarizeFileChainLinks(grouped)).toMatchObject({
      printComplete: 1,
      cutComplete: 1,
      chainStatus: 'PRINTING',
    });
  });
});
